SET(CMAKE_C_COMPILER g++)
SET(CMAKE_CXX_COMPILER g++)

SET(CWARN "-Wall")
SET(COPT "-Os")

SET(CFLAGS "${COPT} ${CWARN}")
SET(CXXFLAGS "${COPT} ${CWARN}")
SET(CMAKE_SHARED_LIBRARY_LINK_CXX_FLAGS "")
SET(CMAKE_EXE_LINK_CXX_FLAGS "--gc-sections")

SET(CMAKE_C_FLAGS  ${CFLAGS})
SET(CMAKE_CXX_FLAGS ${CXXFLAGS})

ADD_DEFINITIONS(-std=c++0x)
